version: '3'

services:
  web:
    environment:
      # Environment-specific settings
      ENVIRONMENT: staging
      DEV_MODE: false
      ALLOW_ADMIN_CHANGES: true
      DISALLOW_ROBOTS: true

      # These variables would be injected by Coolify
      # and not stored in the repository
      # DB_PASSWORD: ${DB_PASSWORD}
      # SECURITY_KEY: ${SECURITY_KEY}
      # PRIMARY_SITE_URL: ${PRIMARY_SITE_URL}
      # REDIS_HOST: redis
      # REDIS_PORT: 6379

  db:
    environment:
      # These would be injected by Coolify
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_PASSWORD: ${DB_PASSWORD}

  queue:
    environment:
      # Environment-specific settings
      ENVIRONMENT: staging
      DEV_MODE: false
      ALLOW_ADMIN_CHANGES: true
      DISALLOW_ROBOTS: true

      # These variables would be inherited from the web service in Coolify
