color: fuchsia
fieldLayouts:
  876abadd-78f0-4dc4-b011-d0da225c4619:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-21T17:57:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f261ad98-97e8-453b-afee-98a876ec7873
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T17:57:31+00:00'
            elementCondition: null
            fieldUid: 4e5f4410-fe03-41d3-a103-8619a3dee7de # Live URL
            handle: null
            includeInCards: false
            instructions: null
            label: URL
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23336cc8-3300-40fe-bba5-80661a778bf0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 763dc329-113b-4ce9-a281-8fb91a68b7b1
        userCondition: null
handle: agency
hasTitleField: true
icon: mace
name: Agency
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
