allowLineBreaksInTitles: false
color: violet
description: null
fieldLayouts:
  8c0171a4-5a7d-428b-bef6-74dd614a7251:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-06-24T14:57:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 38b8a60b-83f6-4c15-990e-7beb1aa71d31
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ad190e45-b0fc-4482-8fc5-d7c953121349
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-27T20:28:18+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c3d4eba5-b940-4c5b-a4cd-6f3d86f6d410
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8446f3b7-fa17-4a71-aa00-8eabb7c7486a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T20:28:18+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 42776a61-f5ef-4385-8543-fb5867a46711
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3617be59-7173-4c18-9158-ce53ab984e05
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T20:28:18+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2cf30ae5-5268-4df7-8be9-54b1dc6e9a88
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1c11f05-43d9-4d8e-b2b3-2b739cc6d4c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T20:28:18+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fa84d361-5db4-4ada-aa90-57a291b972c7
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5e975cd-6b37-47fe-b2a2-0447440ea290
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b173789d-2b26-472b-9d3c-af4fdaf17e69
        userCondition: null
    thumbFieldKey: null
handle: entryJournal
hasTitleField: true
icon: feather
name: 'Entry: Journal'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
