allowLineBreaksInTitles: false
color: violet
description: null
fieldLayouts:
  bdf11e45-a581-46bf-892a-ed49a53f7289:
    cardThumbAlignment: end
    cardView:
      - uri
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-06T11:47:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 93a5014b-ebe6-4c72-bb2c-8afe2016799c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-24T15:05:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3304bc86-e804-4dc5-8c9b-0907003b0734 # Image Asset
            handle: null
            instructions: null
            label: 'Card Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4eedf8db-12dd-41e7-b5e9-8c1a0f100e31
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-24T15:12:12+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 54a2f6b2-d807-4e43-8f06-c42ae89dde90
            userCondition: null
          -
            dateAdded: '2026-06-24T15:12:12+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e8279da5-f90e-4b6c-8c56-239c06e74f6b # Feature Video
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 116ff105-74fa-4299-8964-65f69f20b979
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-24T15:13:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0c63feb6-fcfa-46d6-befd-8445e10a9e7a # Image & Caption
            handle: null
            instructions: null
            label: 'Feature Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75a42628-dab5-4eb3-8b20-685778b33618
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-24T15:13:55+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Video takes precedence if both a video and image are present'
            type: craft\fieldlayoutelements\Tip
            uid: c334d2d4-b513-4264-88b3-74c62ac4a330
            userCondition: null
          -
            dateAdded: '2026-06-24T15:13:55+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: f39b4bbd-5a5b-4e04-8f2a-95195387827d
            userCondition: null
          -
            dateAdded: '2025-01-06T11:47:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9df05e4c-ad18-498a-9fba-144f3ed8f8db # Summary Short
            handle: null
            instructions: null
            label: Summary
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdda0965-32c2-4e39-aac7-016c09bacda7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-06T11:47:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4e5f4410-fe03-41d3-a103-8619a3dee7de # Live URL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e8d849c-d996-4ce0-8cbd-9376d9db5775
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-24T15:33:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5ce6d819-412b-470b-a122-a6d474f65997 # Rich Text Post
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8f5be1c-072d-43d5-8cdc-7ff969b0e7b3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 60097500-d3c0-4650-887d-55df7a025306
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-06T11:47:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f93ff202-7643-4d47-b2cc-126d5595da3f # Work Type
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06fa2e7d-a93d-4c4f-9d84-26f4e93b55fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-06T11:47:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 99701ea9-a4da-4fb6-b997-541f0661f9a9 # Agency
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc84f8c2-c3e6-4a8b-a694-d276f73cca05
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-06T11:47:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c5b973a9-a07d-4d67-acb9-a3f0cbcb1450 # Tech Tags
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e057556-ea98-4302-930d-2323813f26d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-06T11:47:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 52ecdaa0-e78c-4b23-a67b-b2de241c25ac # Year
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27aab770-ab29-482f-9f8e-cfd0a38e20aa
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 6e7bd103-1dc8-48bc-8223-e7d84ce16d0c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-27T20:51:44+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2462263f-d971-4727-b2d2-8cbf1aa3bf8f # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f0c5bd3-52c9-4067-bc69-a50a6e11d9f0
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 846645e5-4382-459f-9c96-b9d47f5e2e3c
        userCondition: null
    thumbFieldKey: 'layoutElement:4eedf8db-12dd-41e7-b5e9-8c1a0f100e31'
handle: entryWork
hasTitleField: true
icon: square-terminal
name: 'Entry: Work'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
uiLabelFormat: '{title}'
