allowLineBreaksInTitles: false
color: violet
description: null
fieldLayouts:
  8c0171a4-5a7d-428b-bef6-74dd614a7251:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-06-24T14:57:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 38b8a60b-83f6-4c15-990e-7beb1aa71d31
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T21:43:44+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9df05e4c-ad18-498a-9fba-144f3ed8f8db # Summary Short
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 593f0005-cc00-48a9-b585-6215a1b221ff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T22:02:45+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c5b973a9-a07d-4d67-acb9-a3f0cbcb1450 # Tech Tags
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dde9750c-9abd-4248-9147-322af68127b8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ad190e45-b0fc-4482-8fc5-d7c953121349
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-27T20:51:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2462263f-d971-4727-b2d2-8cbf1aa3bf8f # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8b7db48-a846-496e-a345-906c6acf179e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b173789d-2b26-472b-9d3c-af4fdaf17e69
        userCondition: null
    thumbFieldKey: null
handle: entryJournal
hasTitleField: true
icon: feather
name: 'Entry: Journal'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
