allowLineBreaksInTitles: false
color: teal
description: null
fieldLayouts:
  57604a88-bf9e-40e2-bbb9-0513bb4f2cf9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-06-25T08:36:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e28b3789-4575-4acb-8e86-a56651a51eac
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-25T08:39:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 68c90757-4b39-4910-94b6-94eb4f0a370b # Rich Text Simple
            handle: null
            instructions: null
            label: 'Short Bio'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39317c4f-3887-4f9d-9976-70ac0d405f9a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-25T08:39:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 68c90757-4b39-4910-94b6-94eb4f0a370b # Rich Text Simple
            handle: richTextSimple2
            instructions: null
            label: 'Full Bio'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abf5eb64-5593-43f4-adb5-1bc6cf9aaa17
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-25T08:39:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4fb7eacc-a8a0-4a3a-8659-9d29b1f619e5 # Tech
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01d3d0a4-428d-4625-af06-370ce67e240a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cfd64066-84d4-4702-835f-71b0ced18427
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-27T20:27:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c3d4eba5-b940-4c5b-a4cd-6f3d86f6d410
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f03783f-2c34-4237-80e1-35d0665df854
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T20:27:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 42776a61-f5ef-4385-8543-fb5867a46711
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d8bb604-beef-45a1-89df-cc7308b9bf2a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T20:27:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2cf30ae5-5268-4df7-8be9-54b1dc6e9a88
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba16c150-990f-4d2f-aa54-9c1cd8630d49
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T20:27:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fa84d361-5db4-4ada-aa90-57a291b972c7
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba2e6ea6-b171-4649-a52d-7304b0b0b6e3
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 1a95148a-9be1-4899-8f8d-7d3928ede0a7
        userCondition: null
    thumbFieldKey: null
handle: pageAbout
hasTitleField: true
icon: moon-over-sun
name: 'Page: About'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
