allowLineBreaksInTitles: false
color: teal
description: null
fieldLayouts:
  57604a88-bf9e-40e2-bbb9-0513bb4f2cf9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-06-25T08:36:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e28b3789-4575-4acb-8e86-a56651a51eac
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-25T08:39:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 68c90757-4b39-4910-94b6-94eb4f0a370b # Rich Text Simple
            handle: null
            instructions: null
            label: 'Short Bio'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39317c4f-3887-4f9d-9976-70ac0d405f9a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-07-02T18:19:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 92f2ad43-f173-454f-92a5-a93e7094cc7b # Bio Sections
            handle: null
            instructions: null
            label: 'Full Bio'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f0b1747-01ca-4fb0-a0e7-22316e7f34a3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-25T08:39:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 68c90757-4b39-4910-94b6-94eb4f0a370b # Rich Text Simple
            handle: richTextSimple2
            instructions: null
            label: 'Full Bio'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abf5eb64-5593-43f4-adb5-1bc6cf9aaa17
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-25T08:39:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4fb7eacc-a8a0-4a3a-8659-9d29b1f619e5 # Tech
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01d3d0a4-428d-4625-af06-370ce67e240a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cfd64066-84d4-4702-835f-71b0ced18427
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-27T20:51:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2462263f-d971-4727-b2d2-8cbf1aa3bf8f # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28c93494-ccc3-48d5-9c0a-ef5d82d1c677
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 1a95148a-9be1-4899-8f8d-7d3928ede0a7
        userCondition: null
    thumbFieldKey: null
handle: pageAbout
hasTitleField: true
icon: moon-over-sun
name: 'Page: About'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
