baseUrl: '@web/cy'
enabled: '1'
handle: cymraeg
hasUrls: true
language: cy-GB
name: 'Huw Roberts | Datblygwr Gwe Llawrydd'
primary: false
siteGroup: 80763c4f-603e-4f78-8e46-e05e80044efe # Huw Roberts
sortOrder: 2
