columnSuffix: null
handle: liveUrl
instructions: null
name: 'Live URL'
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
