columnSuffix: null
handle: richText
instructions: null
name: 'Rich Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  css: null
  cssFile: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  fullGraphqlData: false
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  jsFile: null
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - link
  wordLimit: 60
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
