columnSuffix: null
handle: richTextSimple
instructions: null
name: 'Rich Text Simple'
searchable: false
settings:
  advancedLinkFields:
    - target
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: true
  headingLevels:
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - link
    - '|'
    - insertImage
    - bulletedList
    - numberedList
    - '|'
    - code
    - codeBlock
    - outdent
    - indent
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
