columnSuffix: null
handle: summaryShort
instructions: "May be used in meta description tag and/or in main content (e.g. cards)\r\n"
name: 'Summary Short'
searchable: false
settings:
  byteLimit: null
  charLimit: 200
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
