defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b72f3694-5d2a-478c-badd-08344714d7d0 # Entry: Agency
handle: agency
maxAuthors: 1
minAuthors: 1
name: Agency
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  25a33ae6-3901-458a-8998-5f63d864a3f3: # Default
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 548fdbe3-a33a-4e69-8c8e-54e4752cc567
type: structure
