defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c0160475-3256-40fc-89bf-3e63d0add54c # Page: Home
handle: home
maxAuthors: 1
minAuthors: 1
name: Home
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  25a33ae6-3901-458a-8998-5f63d864a3f3: # Default
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: __home__
type: single
