defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 42a845ce-2d17-4963-951a-a0d7508a1219 # Page: Journal Index
handle: journalIndex
maxAuthors: 1
minAuthors: 1
name: 'Journal (Index)'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  25a33ae6-3901-458a-8998-5f63d864a3f3: # Default
    enabledByDefault: true
    hasUrls: true
    template: journal/_index.twig
    uriFormat: '{slug}'
type: single
