defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 42a845ce-2d17-4963-951a-a0d7508a1219 # Page: Post Index
handle: postsIndex
maxAuthors: 1
minAuthors: 1
name: 'Posts: Index'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  25a33ae6-3901-458a-8998-5f63d864a3f3: # Default
    enabledByDefault: true
    hasUrls: true
    template: posts-index/_entry.twig
    uriFormat: posts-index
type: single
