defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4ffac4bc-7b4a-4579-9cc7-8dd3074e1e83 # Entry: Post
handle: posts
maxAuthors: 1
minAuthors: 1
name: Posts
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  25a33ae6-3901-458a-8998-5f63d864a3f3: # Default
    enabledByDefault: true
    hasUrls: true
    template: posts/_entry.twig
    uriFormat: 'posts/{slug}'
type: channel
