defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c300fa12-7356-4389-b8d8-0411927605a8 # Page: Who
handle: who
maxAuthors: 1
minAuthors: 1
name: Who
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  25a33ae6-3901-458a-8998-5f63d864a3f3: # Default
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
