defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ad34d564-b010-4b10-9cbe-473ebc2699ff # Work Index
handle: workIndex
maxAuthors: 1
minAuthors: 1
name: 'Work (Index)'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5d7df7d1-586e-49d0-a3ed-d6d76e75ca7c: # Cymraeg
    enabledByDefault: true
    hasUrls: true
    template: work/_index.twig
    uriFormat: '{slug}'
  25a33ae6-3901-458a-8998-5f63d864a3f3: # English
    enabledByDefault: true
    hasUrls: true
    template: work/_index.twig
    uriFormat: '{slug}'
type: single
